--
-- PostgreSQL database dump
--

-- Dumped from database version 17.0 (Debian 17.0-1.pgdg120+1)
-- Dumped by pg_dump version 17.0 (Debian 17.0-1.pgdg120+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: ToDoItems; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."ToDoItems" (
    "Id" integer NOT NULL,
    "Title" text NOT NULL,
    "Description" text NOT NULL,
    "Date" date NOT NULL,
    "UserId" integer NOT NULL
);


--
-- Name: ToDoItems_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."ToDoItems" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."ToDoItems_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Users" (
    "Id" integer NOT NULL,
    "Username" text NOT NULL,
    "PasswordHash" text NOT NULL,
    "RefreshToken" text,
    "RefreshTokenExpirationDate" timestamp with time zone
);


--
-- Name: Users_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."Users" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Users_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


--
-- Data for Name: ToDoItems; Type: TABLE DATA; Schema: public; Owner: -
--

---Here starts data


-- COPY public."ToDoItems" ("Id", "Title", "Description", "Date", "UserId") FROM stdin;
-- 1	Zakupy	Zrobić zakupy na wyjazd	2025-06-26	1
-- 2	Bieganie	20km bieg	2025-06-27	1
-- 11	Napisać dockerfile	Należy przygotować plik dockerfile w celu konteneryzacji aplikacji	2025-07-02	1
-- 3	Pisanie rozprawki	Napisać rozprawkę nt. Migracji i kultury	2025-06-30	1
-- \.


-- --
-- -- Data for Name: Users; Type: TABLE DATA; Schema: public; Owner: -
-- --

-- COPY public."Users" ("Id", "Username", "PasswordHash", "RefreshToken", "RefreshTokenExpirationDate") FROM stdin;
-- 2	Adam	AQAAAAIAAYagAAAAEMulO0rEwkd4lTnFVhtW6tB3qhTmxxK/aSXoq0PL1az9zqDhDUJD1P+mO1naifBmZg==	\N	\N
-- 3	Jan	AQAAAAIAAYagAAAAEFDvc1xlcmDMEn7R1LgOne0R7tLly5zf5LFg8pA/jU2bi83ZRcFXoEW2cGnco4p5Og==	\N	\N
-- 1	Szymon	AQAAAAIAAYagAAAAEMmTieOjt4kDCoNWSXPrxXHkbTxuYBNPa7G4ObxfE3NC6aPZidlbczLiSNkunqcDWw==	Oe3NAZGY7Acp5ROxrMxLFetpVq8hKfZJ7Cks6LQoG4E=	2025-07-04 17:21:06.613478+00
-- \.


-- --
-- -- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: -
-- --

-- COPY public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") FROM stdin;
-- 20250626152230_Initial	9.0.6
-- 20250626181635_AddRefreshTokens	9.0.6
-- 20250626221010_ChangeToDateOnly	9.0.6
-- \.


-- --
-- -- Name: ToDoItems_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
-- --

-- SELECT pg_catalog.setval('public."ToDoItems_Id_seq"', 11, true);


-- --
-- -- Name: Users_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
-- --

-- SELECT pg_catalog.setval('public."Users_Id_seq"', 4, true);


---Here ends data

--
-- Name: ToDoItems PK_ToDoItems; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ToDoItems"
    ADD CONSTRAINT "PK_ToDoItems" PRIMARY KEY ("Id");


--
-- Name: Users PK_Users; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Users"
    ADD CONSTRAINT "PK_Users" PRIMARY KEY ("Id");


--
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- Name: IX_ToDoItems_UserId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_ToDoItems_UserId" ON public."ToDoItems" USING btree ("UserId");


--
-- Name: ToDoItems FK_ToDoItems_Users_UserId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ToDoItems"
    ADD CONSTRAINT "FK_ToDoItems_Users_UserId" FOREIGN KEY ("UserId") REFERENCES public."Users"("Id") ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

